-- 20260930_12_permissions_defauts_registre_complet.sql
-- Droits app-level, phase 4 (étape 1) : défauts app regénérés depuis le registre
-- src/lib/permissionsRegistry.js (node scripts/gen-app-role-permissions-sql.mjs).
--
-- Nouveautés par rapport au seed de juin (111 lignes) :
--   - pv_calculator.view / thermal_study.view : responsable et commercial oui, technicien non.
--     Jusqu'ici ces ressources (RouteGuard Solaire / Thermique) n'existaient qu'en surcharges
--     posées à la main chez Mayer et Cimaj ; une org sans ces lignes ne voyait ni Solaire ni
--     Thermique pour ses non-admins, sans erreur (role_can fail-closed).
--   - maintenance.view / maintenance.edit : présents dans le registre depuis 20260925_1, jamais
--     seedés en base → role_can répondait faux là où l'écran répondait vrai.
-- Aucun changement de comportement pour Mayer / Cimaj (leurs surcharges portent déjà ces valeurs).
-- Idempotent (upsert sur la clé primaire role, resource, action).
INSERT INTO majordhome.app_role_permissions (role, resource, action, allowed) VALUES
  ('team_leader','dashboard','view',true),
  ('commercial','dashboard','view',true),
  ('technicien','dashboard','view',true),
  ('team_leader','clients','view',true),
  ('commercial','clients','view',true),
  ('technicien','clients','view',true),
  ('team_leader','clients','create',true),
  ('commercial','clients','create',true),
  ('technicien','clients','create',false),
  ('team_leader','clients','edit',true),
  ('commercial','clients','edit',true),
  ('technicien','clients','edit',true),
  ('team_leader','clients','delete',false),
  ('commercial','clients','delete',false),
  ('technicien','clients','delete',false),
  ('team_leader','pipeline','view',true),
  ('commercial','pipeline','view',true),
  ('technicien','pipeline','view',false),
  ('team_leader','pipeline','create',true),
  ('commercial','pipeline','create',true),
  ('technicien','pipeline','create',false),
  ('team_leader','pipeline','edit',true),
  ('commercial','pipeline','edit',false),
  ('technicien','pipeline','edit',false),
  ('team_leader','pipeline','edit_own',true),
  ('commercial','pipeline','edit_own',true),
  ('technicien','pipeline','edit_own',false),
  ('team_leader','pipeline','delete',false),
  ('commercial','pipeline','delete',false),
  ('technicien','pipeline','delete',false),
  ('team_leader','pipeline','assign',true),
  ('commercial','pipeline','assign',false),
  ('technicien','pipeline','assign',false),
  ('team_leader','chantiers','view',true),
  ('commercial','chantiers','view',true),
  ('technicien','chantiers','view',true),
  ('team_leader','chantiers','edit',true),
  ('commercial','chantiers','edit',false),
  ('technicien','chantiers','edit',false),
  ('team_leader','chantiers','edit_own',true),
  ('commercial','chantiers','edit_own',true),
  ('technicien','chantiers','edit_own',true),
  ('team_leader','planning','view',true),
  ('commercial','planning','view',true),
  ('technicien','planning','view',true),
  ('team_leader','planning','create',true),
  ('commercial','planning','create',true),
  ('technicien','planning','create',false),
  ('team_leader','entretiens','view',true),
  ('commercial','entretiens','view',true),
  ('technicien','entretiens','view',true),
  ('team_leader','entretiens','create',true),
  ('commercial','entretiens','create',true),
  ('technicien','entretiens','create',true),
  ('team_leader','entretiens','edit',true),
  ('commercial','entretiens','edit',false),
  ('technicien','entretiens','edit',true),
  ('team_leader','sav','view',true),
  ('commercial','sav','view',true),
  ('technicien','sav','view',true),
  ('team_leader','sav','create',true),
  ('commercial','sav','create',false),
  ('technicien','sav','create',false),
  ('team_leader','sav','edit',true),
  ('commercial','sav','edit',false),
  ('technicien','sav','edit',false),
  ('team_leader','devis','view',true),
  ('commercial','devis','view',true),
  ('technicien','devis','view',false),
  ('team_leader','devis','create',true),
  ('commercial','devis','create',true),
  ('technicien','devis','create',false),
  ('team_leader','devis','edit',true),
  ('commercial','devis','edit',true),
  ('technicien','devis','edit',false),
  ('team_leader','devis','delete',false),
  ('commercial','devis','delete',false),
  ('technicien','devis','delete',false),
  ('team_leader','tasks','view',true),
  ('commercial','tasks','view',true),
  ('technicien','tasks','view',true),
  ('team_leader','tasks','create',true),
  ('commercial','tasks','create',true),
  ('technicien','tasks','create',true),
  ('team_leader','tasks','edit',true),
  ('commercial','tasks','edit',false),
  ('technicien','tasks','edit',false),
  ('team_leader','tasks','edit_own',false),
  ('commercial','tasks','edit_own',true),
  ('technicien','tasks','edit_own',false),
  ('team_leader','tasks','delete',false),
  ('commercial','tasks','delete',false),
  ('technicien','tasks','delete',false),
  ('team_leader','tasks','assign',true),
  ('commercial','tasks','assign',false),
  ('technicien','tasks','assign',false),
  ('team_leader','territoire','view',true),
  ('commercial','territoire','view',true),
  ('technicien','territoire','view',true),
  ('team_leader','meta_ads','view',false),
  ('commercial','meta_ads','view',false),
  ('technicien','meta_ads','view',false),
  ('team_leader','voice_recorder','use',true),
  ('commercial','voice_recorder','use',false),
  ('technicien','voice_recorder','use',false),
  ('team_leader','pv_calculator','view',true),
  ('commercial','pv_calculator','view',true),
  ('technicien','pv_calculator','view',false),
  ('team_leader','thermal_study','view',true),
  ('commercial','thermal_study','view',true),
  ('technicien','thermal_study','view',false),
  ('team_leader','maintenance','view',true),
  ('commercial','maintenance','view',true),
  ('technicien','maintenance','view',true),
  ('team_leader','maintenance','edit',false),
  ('commercial','maintenance','edit',false),
  ('technicien','maintenance','edit',false),
  ('team_leader','settings','view',false),
  ('commercial','settings','view',false),
  ('technicien','settings','view',false),
  ('team_leader','settings','edit',false),
  ('commercial','settings','edit',false),
  ('technicien','settings','edit',false)
ON CONFLICT (role, resource, action) DO UPDATE SET allowed = EXCLUDED.allowed;
